print("Hello world!")
name = input("Ваше ФИО: ")
age = input("Введите вас возраст: ")
region = input("Ваша страна и регион проживания: ")
drink = input("Ваш любимый напиток😎: ")
food = input("Ваше любимое блюдо: ")
game = input("Ваша любимая игра: ")
print(name + " ваше ФИО")
print(age + " ваш возраст")
print(region + " ваша страна и регион проживания")
print(drink + " ваш любимый напиток😎")
print(food + " ваше любимое блюдо")
print(food + " ваши любимые игры")