print( "Привет Мир!" )
print( "Hello, world!" )
print( "Bonjour, le monde!!" )
print( "¡Hola, Mundo!" )
print( "Hallo, Welt!" )
print( "Ciao, Mondo!" )
print( "こんにちは、世界！" )
print( "你好，世界!" )
print( "नमस्ते, दुनिया!" )
print( "ا، يا عالم !مرحب" )