names = ["Аня", "Боря", "Вика"]
print(names)
for i in range(len(names)):
    print("элемент", i, "это", names[i])
names.append("Катя")
print(names)
names.insert(1, "Вова")
print(names)
names.remove("Катя")
print(names)
last_name = names.pop()
print(last_name)
print(names)
print(len(names))
names.sort(reverse=True)
print(names)
names.sort()
print(names)
names.reverse()
print(names)